apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conexao-service.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "conexao-service.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
