apiVersion: v1
kind: ConfigMap
metadata:
  name: hackatonfiap-payments-config
  namespace: conexao-solidaria
  labels:
    app.kubernetes.io/name: hackatonfiap-payments
    app.kubernetes.io/part-of: conexao-solidaria
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "conexaosolidaria.local"
  Jwt__Audience: "conexaosolidaria.clients"
  ServiceBus__RequestTopic: "donation-requested"
  ServiceBus__Subscription: "payments"
  ServiceBus__ResultTopic: "payment-result"
