apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackatonfiap-payments
  namespace: conexao-solidaria
  labels:
    app.kubernetes.io/name: hackatonfiap-payments
    app.kubernetes.io/part-of: conexao-solidaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hackatonfiap-payments
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hackatonfiap-payments
        app.kubernetes.io/part-of: conexao-solidaria
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: hackatonfiap-payments
          image: hackatonfiap-payments:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: hackatonfiap-payments-config
            - secretRef:
                name: hackatonfiap-payments-secret
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
